---

# Need 2 steps, known issue with ansible. See for example https://github.com/xsnippet/xsnippet-infra/pull/26/commits/04b0c74870a15429f71e924600135bba8948f3ee

- name: webadaptor_start_check_existance_of_webadaptor_installation_sources
  stat:
    path: /data/installsource/WebAdaptor
  register: installsourceWebAdaptor

- name: First download ArcGIS_WebAdaptor_Linux tar file 
  get_url:
    url: "https://gisautomation.s3.eu-central-1.amazonaws.com/ArcGIS_Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz"
    dest: "/data/tmp/Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz"
    tmp_dest: /data/tmp
  when: not installsourceWebAdaptor.stat.exists

# - name: copy web adaptor file from mngmnt to remote node. first changes the dir to somedir/
#   ansible.builtin.shell: "scp -p 22 <location of the file on mngmnt vm> user@nodeIp:locationOnNode"
#     chdir: somedir/

# - name: Copy install files 
#   copy:
#     src: /data/ansible/files/ArcGIS_Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz
#     dest: /data/tmp/ArcGIS_Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz
#     owner: azureuser
#     group: azureuser
#     mode: '0640'
#   when: not installsourceWebAdaptor.stat.exists

- name: Extract ArcGIS_DataStore_Linux tar file
  unarchive:
    src: "/data/tmp/Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz"
    dest: /data/installsource
    remote_src: true
  when: not installsourceWebAdaptor.stat.exists

- name: Cleanup Web_Adaptor_Java_Linux tar.gz file
  file:
    state: absent
    path: "/data/tmp/Web_Adaptor_Java_Linux_{{ arcgiswebadaptorfileversion }}.tar.gz"

- name: Install WebAdaptor
  shell: cd /data/installsource/WebAdaptor/;./Setup -m silent -l yes -d /data 2>&1| tee /data/tmp/install.log
  become_user: azureuser
  args:
    creates: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/arcgis.war"
  register: WebAdaptorinstalled

- name: wa installation debug
  debug:
    var: WebAdaptorinstalled

- name: Copy arcgis.war for portal
  become_user: azureuser
  copy:
    src: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/arcgis.war"
    dest: /data/arcgis/tomcat/webapps/arcgis.war
    remote_src: true

- name: Copy arcgis.war for server
  become_user: azureuser
  copy:
    src: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/arcgis.war"
    dest: /data/arcgis/tomcat/webapps/server.war
    remote_src: true

- name: wait for portal to start
  wait_for: timeout=90
  when: WebAdaptorinstalled.changed

# - name: Register portal with webadaptor
#   shell: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/tools/configurewebadaptor.sh -m portal -w https://{{groups['arcgiswebportal'][0]}}/arcgis/webadaptor -g https://{{groups['arcgisportal'][0]}}:7443 -u portaladmin -p {{ portaladminpassword }} -a false"
#   become_user: azureuser
#   environment: 
#     PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/data/arcgis/jdk/bin
#   register: resp
#   #when: WebAdaptorinstalled.changed

- name: get portal server fqdn
  shell: "nslookup {{groups['arcgisportal'][0]}} | grep 'Name' | cut -c 7-"
  tags: dev
  become_user: azureuser
  register: portalserverfqdn

- name: portal get fqdn debug
  debug:
    var: portalserverfqdn
  tags: dev

# - name: Register portal with webadaptor
#   shell: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/tools/configurewebadaptor.sh -m portal -w https://{{portalserverfqdn['stdout']}}:8443/arcgis/webadaptor -g https://{{portalserverfqdn['stdout']}}:7443 -u portaladmin -p {{ portaladminpassword }} -a false"
#   become_user: azureuser
#   environment: 
#     PATH: /data/arcgis/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
#   register: resp
#   #when: WebAdaptorinstalled.changed

- name: Register portal with webadaptor
  shell: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/tools/configurewebadaptor.sh -m portal -w https://{{webserverfqdn}}/arcgis/webadaptor -g https://{{portalserverfqdn['stdout']}}:7443 -u portaladmin -p {{ portaladminpassword }} -a false"
  become_user: azureuser
  environment: 
    PATH: /data/arcgis/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  register: resp
  #when: WebAdaptorinstalled.changed

- name: debug portal registration
  debug:
   var: resp

- name: get ags server fqdn
  shell: "nslookup {{groups['arcgisserver'][0]}} | grep 'Name' | cut -c 7-"
  tags: dev
  become_user: azureuser
  register: arcgisserverfqdn

- name: arcgisds get fqdn debug
  debug:
    var: arcgisserverfqdn
  tags: dev

# - name: Register server with webadaptor
#   shell: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/tools/configurewebadaptor.sh -m server -w https://{{arcgisserverfqdn['stdout']}}:8443/server/webadaptor -g https://{{arcgisserverfqdn['stdout']}}:6443 -u siteadmin -p {{ siteadminpassword }} -a false"
#   become_user: azureuser
#   environment:
#     PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usrscp -r ../ansible azureuser@13.95.163.241:/data/sbin:/data/arcgis/jdk/bin
#   register: ress
#   #when: WebAdaptorinstalled.changed 

- name: Register server with webadaptor
  shell: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/tools/configurewebadaptor.sh -m server -w https://{{webserverfqdn}}/server/webadaptor -g https://{{arcgisserverfqdn['stdout']}}:6443 -u siteadmin -p {{ siteadminpassword }} -a false"
  become_user: azureuser
  environment:
    PATH: /data/arcgis/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  register: ress
  #when: WebAdaptorinstalled.changed

- name: server registration debug
  debug:
    var: ress
#- name: copy tomcat favicon to favicon.old
 # copy:
   # src: /data/arcgis/tomcat/webapps/ROOT/favicon.ico
   # dest: /data/arcgis/tomcat/webapps/ROOT/favicon.ico.old
   # remote_src: true

#- name: copy arcgis favicon to tomcat root
 # copy:
   # src: "/data/arcgis/webadaptor{{ arcgiswebadapterpathversion }}/java/WebAdaptorHelp/en/include/images/favicon.ico"
    #dest: /data/arcgis/tomcat/webapps/ROOT/favicon.ico
    #remote_src: true 
